configfile: "config/config.yaml"

ruleorder: pipeline_entry > parcellation

mouses 		= config["branch_opts"]["mouses"]
dates		= config["branch_opts"]["dates"]
parcellations	= config["branch_opts"]["parcellations"]
filters		= config["branch_opts"]["filters"]

conditions	= config["branch_opts"]["conditions"]
if conditions is None:
	sides			= config["trial_conditions"]["sides"]["conds"]
	modalities		= config["trial_conditions"]["modalities"]["conds"]

	trial_conditions	= { f"{side}_{modal}" : {"modality" : m, "target_side_left" : s}
					for side,s in sides.items() for modal,m in modalities.items()}
	phase_conditions	= dict.fromkeys(trial_conditions.keys(),"stimulus")
else:
	trial_condition		= config["trial_conditions"]
	phase_condition		= config["phase_conditions"]
	trial_conditions	= { label :
					{ trial_condition[condition]["column"] : trial_condition[condition]["conds"][key]
						for condition, key in conds.items() if condition != "phase" }
					for label, conds in conditions.items() }
	phase_conditions	= { label : phase_condition[conds["phase"]] if "phase" in conds else None
					for label, conds in conditions.items() }


features	= config["features"]

decoders	= config["decode_opts"]["decoders"]
k_folds 	= config["decode_opts"]["k_folds"]

wildcard_constraints:
	mouse		= r"[a-zA-Z\d_]+",
	parcellation	= r"[a-zA-Z\d_]+",
	filter		= r"[a-zA-Z\d_]+",
	cond		= r"[a-zA-Z\d_]+",
	feature		= r"[a-zA-Z\d_]+",
	decoder		= r"[a-zA-Z\d_]+",



###   Output accumulation rules   ###

# The first rule is default
rule all:
	input:
		[f"results/{mouse}/{parcellation}/{filter}/decoder/performances.png"
			   for mouse in mouses
			   for parcellation in parcellations
			   for filter in filters],
		[ f"results/{mouse}/{parcellation}/{filter}/decoder/{feature}/plots/performance.png"
					for mouse in mouses
					for parcellation in parcellations
					for filter in filters
					for cond in trial_conditions.keys()
					for feature in features],

rule all_plots:
	input:
		 [ f"results/{mouse}/{parcellation}/{filter}/decoder/{feature}/plots/performance.png"
			   for mouse in mouses
			   for parcellation in parcellations
			   for filter in filters
			   for cond in trial_conditions.keys()
			   for feature in features]

rule all_decode:
	input:
		[ f"results/{mouse}/{parcellation}/{filter}/decoder/{feature}/{decoder}/decoder_model.pkl"
				for mouse in mouses
				for parcellation in parcellations
				for filter in filters
				for cond in trial_conditions.keys()
				for feature in features
				for decoder in decoders]

rule all_features:
	input:
		[ f"results/{mouse}/{parcellation}/{filter}/{cond}/{feature}/feature_data.h5"
				for mouse in mouses
				for parcellation in parcellations
				for filter in filters
				for cond in trial_conditions.keys()
				for feature in features ]



###   Data processing   ###

rule pipeline_entry:
	input:
		tasks	= [ f"resources/experiment/{{mouse}}/{date}/task_data/"
				for date in dates ],
		Vc	= [ f"resources/experiment/{{mouse}}/{date}/SVD_data/Vc.mat"
				for date in dates ],
		trans_params = [ f"resources/experiment/{{mouse}}/{date}/SVD_data/opts.mat"
				  for date in dates ],
	output:
		"results/{mouse}/SVD/data.h5",
		config = "results/{mouse}/SVD/conf.yaml",
	log:
		"results/{mouse}/SVD/pipeline_entry.log"
	conda:
		"envs/environment.yaml"
	resources:
		memb_mb=1000
	script:
		"scripts/default_entry.py"

def parcellation_input(wildcards):
	input = {
		"data"	: "results/{mouse}/SVD/data.h5",
		"config": "results/{mouse}/SVD/conf.yaml" }
	input["meta"]	= config["parcellation_opts"]["paths"][wildcards["parcellation"]]
	return input

rule parcellation:
	input:
		unpack(parcellation_input)
	output:
		"results/{mouse}/{parcellation}/data.h5",
		config = "results/{mouse}/{parcellation}/conf.yaml",
	wildcard_constraints:
		parcellation = "(?!SVD).+"
	log:
		"results/{mouse}/{parcellation}/parcellation.log"
	conda:
		"envs/environment.yaml"
	resources:
		memb_mb=1000
	script:
		"scripts/parcellation.py"

rule prefilters:
	input:
		"results/{mouse}/{parcellation}/data.h5",
		config = "results/{mouse}/{parcellation}/conf.yaml",
	output:
		"results/{mouse}/{parcellation}/{filter}/filtered_data.h5",
		config = "results/{mouse}/{parcellation}/{filter}/conf.yaml",
	log:
		"results/{mouse}/{parcellation}/{filter}/prefilters.log"
	conda:
		"envs/environment.yaml"
	resources:
		memb_mb=1000
	script:
		"scripts/prefilter.py"

def condition_params(wildcards):
	params = {
		"trial_conditions" : { wildcards["cond"] : trial_conditions[wildcards["cond"]]},
		"phase_conditions" : { wildcards["cond"] : phase_conditions[wildcards["cond"]]},
	}
	return params

rule condition:
	input:
		"results/{mouse}/{parcellation}/{filter}/filtered_data.h5",
		config = "results/{mouse}/{parcellation}/{filter}/conf.yaml",
	output:
		"results/{mouse}/{parcellation}/{filter}/{cond}/conditional_data.h5",
		config = "results/{mouse}/{parcellation}/{filter}/{cond}/conf.yaml",
	params:
		condition_params
	log:
		"results/{mouse}/{parcellation}/{filter}/{cond}/conditionals.log"
	conda:
		"envs/environment.yaml"
	resources:
		memb_mb=1000
	script:
		"scripts/conditional.py"

rule feature_calculation:
	input:
		"results/{mouse}/{parcellation}/{filter}/{cond}/conditional_data.h5",
		config = "results/{mouse}/{parcellation}/{filter}/{cond}/conf.yaml",
	output:
		"results/{mouse}/{parcellation}/{filter}/{cond}/{feature}/feature_data.h5",
		config = "results/{mouse}/{parcellation}/{filter}/{cond}/{feature}/conf.yaml",
	log:
		"results/{mouse}/{parcellation}/{filter}/{cond}/{feature}/feature_calculation.log"
	conda:
		"envs/environment.yaml"
	resources:
		memb_mb=1000
	script:
		"scripts/feature.py"

rule decoding:
	input:
		[f"results/{{mouse}}/{{parcellation}}/{{filter}}/{cond}/{{feature}}/feature_data.h5" for cond in trial_conditions.keys()],
	output:
		"results/{mouse}/{parcellation}/{filter}/decoder/{feature}/{decoder}/decoder_model.pkl",
		"results/{mouse}/{parcellation}/{filter}/decoder/{feature}/{decoder}/decoder_perf.pkl",
		config = "results/{mouse}/{parcellation}/{filter}/decoder/{feature}/{decoder}/conf.yaml",
	params:
		conds = list(trial_conditions.keys()),
		reps = k_folds,
	log:
	   "results/{mouse}/{parcellation}/{filter}/decoder/{feature}/{decoder}/decoding.log",
	conda:
		"envs/environment.yaml"
	resources:
		memb_mb=1000
	script:
		"scripts/decoding.py"



###   Plotting   ###

rule plot_performance:
	input:
		[f"results/{{mouse}}/{{parcellation}}/{{filter}}/decoder/{{feature}}/{decoder}/decoder_perf.pkl" for decoder in decoders],
	output:
		"results/{mouse}/{parcellation}/{filter}/decoder/{feature}/plots/performance.png",
		"results/{mouse}/{parcellation}/{filter}/decoder/{feature}/plots/performance.pkl",
	params:
		conds=list(trial_conditions.keys()),
		decoders=decoders,
	log:
		"results/{mouse}/{parcellation}/{filter}/decoder/{feature}/plots/plot_performance.log",
	conda:
		 "envs/environment.yaml"
	script:
		  "scripts/plot_performance.py"

rule plot_performances:
	input:
		[f"results/{{mouse}}/{{parcellation}}/{{filter}}/decoder/{feature}/{decoder}/decoder_perf.pkl"
				for feature in features
				for decoder in decoders],
	output:
		"results/{mouse}/{parcellation}/{filter}/decoder/performances.png",
	params:
		conds=list(trial_conditions.keys()),
		decoders=decoders,
		features=features,
	log:
		"results/{mouse}/{parcellation}/{filter}/decoder/plot_performances.log",
	conda:
		 "envs/environment.yaml"
	script:
		  "scripts/plot_performances.py"



rule debug:
	input:
		tasks	= [ f"resources/experiment/{mouse}/{date}/task_data/"
				for date in dates for mouse in mouses ],
	conda:
		"envs/environment.yaml"
	log:
		"results/debug.log"
	script:
		"scripts/debug_snakemake.py"



###   legacy tests   ###

rule test_data:
	input:
		"results/GN06/SVD/data.h5"
	log:
		"results/GN06/SVD/test_data.log"
	conda:
		"envs/environment.yaml"
	script:
		"code/test_data.py"

rule test_analysis:
	input:
		"results/GN06/SVD/data.h5"
	log:
		"results/GN06/SVD/test_analysis.log"
	conda:
		"envs/environment.yaml"
	script:
		"code/test_analysis.py"
