branch_opts:
  combine_sessions: False

  # Random SVD and Metadata is created as experimental data
  subjects:
    random:
      - random

  # Defines conditions for analog to Gerions Experimental Setup, however the corresponding metadata in the experiment is completly randomized
  conditions:
    default:
      phase: all 
      #n_targets: all
      #n_distractors: none
      auto_reward: no
      both_spouts: yes


    ### Choice Decoder
    #_leftResponse_leftStim:
    #  responses: left
    #  sides: left

    #_leftResponse_rightStim:
    #  responses: left
    #  sides: right

    #_rightResponse_rightStim:
    #  responses: right
    #  sides: right

    #_rightResponse_leftStim:
    #  responses: right
    #  sides: left

    #_noResponse:
    #  responses: no

    #Stimulus Decoder
    left:
      sides: left
    right:
      sides: right

    #visual:
    #  modalities: visual
    #tactile:
    #  modalities: tactile
    #multisensory:
    #  modalities: vistact

    #left_visual:
    #  sides: left
    #  modalities: visual
    #right_visual:
    #  sides: right
    #  modalities: visual
    # left_tactile:
    #   sides: left
    #   modalities: tactile
    # right_tactile:
    #   sides: right
    #   modalities: tactile
    #left_vistact:
    #  sides: left
    #  modalities: vistact
    #right_vistact:
    #  sides: right
    #  modalities: vistact


# Defines trial phases for Gerions Experimental Setup
trial_conditions:
  sides:
    column: target_side_left
    conds:
      left:   1
      right:  0
  modalities:
    column: modality
    conds:
      visual:   0
      tactile:  1
      vistact:  2
  responses:
    column: response_left
    conds:
      left: 1
      right: 0
      no: -1
  n_targets:
    column: n_targets
    conds:
      all: 6
  n_distractors:
    column: n_distractors
    conds:
      none: 0
  auto_reward:
    column: auto_reward
    conds:
      no: 0
      yes: 1
  both_spouts:
    column: both_spouts
    conds:
      no: 0
      yes: 1

phase_conditions:
  pretrial:
    start: 0
    stop:  7
  posttrial:
    start: 113
    stop: 133
  stimulus:
    start:  30
    stop:   75
  delay:
    start: 75
    stop: 83
  response:
    start: 83
    stop: 113
  w_response:
    start: 30
    stop: 83
  all:
    start: 0
    stop: 134