branch_opts:
  combine_sessions: True #Combine sessions (upon loading) & find new spatials with PCA / Combine sessions (after feature calculation) based on original spatials (noisy if spatials are different)
  include_individual_sessions: True #False #Run pipeline on individual sessions and combined sessions / just on combined session

  subjects:
    #random:
    #  - random

    # Defines subjects and dates to use from Gerions Experiment
    GN06:
      - "2021-03-26"
      - "2021-03-29"
      #- 2021-04-01_13-44-22
      - "2021-03-01"
      - "2021-03-02"
      - "2021-03-03"
      - "2021-03-04"

    GN09:
      - "2021-03-26"
      - "2021-04-14"
      - "2021-04-15_11"
      - "2021-04-15_15"
      - "2021-04-16"
      - "2021-04-19"
      - "2021-04-20"
      - "2021-04-21"


    #GN08:
    # - 2021-03-26_13-37-18
    #  - 2021-03-29_13-37-29
    #  - 2021-03-29_16-33-41
    
    #GN10:
    #  - 2021-03-29_15-41-22
    #  - 2021-03-29_15-41-22
    #  - 2021-04-21_11-00-51

  # Defines conditions for Gerions Experimental Setup
  conditions:
    default:
      phase: all
      n_targets: all
      n_distractors: none
      auto_reward: no
      both_spouts: yes


    ### Choice Decoder
    # leftResponse_leftStim:
    #   responses: left
    #   sides: left

    # leftResponse_rightStim:
    #   responses: left
    #   sides: right

    # rightResponse_rightStim:
    #   responses: right
    #   sides: right

    # rightResponse_leftStim:
    #   responses: right
    #   sides: left

    # noResponse:
    #   responses: no

    #Stimulus Decoder
    #left:
    #  sides: left
    #right:
    #  sides: right

    #visual:
    #  modalities: visual
    #tactile:
    #  modalities: tactile
    #multisensory:
    #  modalities: vistact

    #Stimulus Decoder
    left_visual:
      sides: left
      modalities: visual
    right_visual:
      sides: right
      modalities: visual
    left_tactile:
      sides: left
      modalities: tactile
    right_tactile:
      sides: right
      modalities: tactile
    left_vistact:
      sides: left
      modalities: vistact
    right_vistact:
      sides: right
      modalities: vistact


# Defines trial phases for Gerions Experimental Setup
trial_conditions:
  sides:
    column: target_side_left
    conds:
      left:   1
      right:  0
  modalities:
    column: modality
    conds:
      visual:   0
      tactile:  1
      vistact:  2
  responses:
    column: response_left
    conds:
      left: 1
      right: 0
      no: -1
  n_targets:
    column: n_targets
    conds:
      all: 6
  n_distractors:
    column: n_distractors
    conds:
      none: 0
  auto_reward:
    column: auto_reward
    conds:
      no: 0
      yes: 1
  both_spouts:
    column: both_spouts
    conds:
      no: 0
      yes: 1

phase_conditions:
  pretrial:
    start: 0
    stop:  30
  posttrial:
    start: 112.5
    stop: 134
  stimulus:
    start:  30
    stop:   75
  delay:
    start: 75
    stop: 82.5
  response:
    start: 82.5
    stop: 112.5
  all:
    start: 0
    stop: 134