branch_opts:
  combine_sessions: True #Combine sessions (upon loading) & find new spatials with PCA / Combine sessions (after feature calculation) based on original spatials (noisy if spatials are different)
  include_individual_sessions: False #False #Run pipeline on individual sessions and combined sessions / just on combined session

  subjects:
    #random:
    #  - random

    # Defines subjects and dates to use from Gerions Experiment
    GN06:
    # Working Datasets
       - "03-26"
       - "03-29"

    # Only few unsuccesful trials  
       - "04-01"

    # New Vc.mat missing
    #  - "01-20"
    #  - "03-01"
    #  - "03-02"
    #  - "03-03"
    #  - "03-04"
    #  - "03-05"

    # Old files missing
    # - "03-25"

    GN09:
    # Working Datasets
      - 03-26_10
      - 04-14_16
      - 04-15_15
      - 04-16_15
    
    # Only few unsuccesful trials 
      - 04-15_11 
      - 04-19_10 

    # New Vc.mat missing (currently)
    #  #- 04-20_13
    #  #- 04-21_13

    GN08:
    # Working Datasets
      - "03-26"
      - "03-29_13"

    # Only few unsuccesful trials 
      - "03-29_16" 

    ### Old files missing
    #- 03-25_11 
    #- 03-25_15 

    # new Vc.mat missing
    # - "03-01_15"
    # - "03-02_17"
    # - "03-03"
    # - "03-04"
    # - "03-05"
    
    GN10:
    # Working Datasets
    - "03-29_15"
    - "04-12_09"
    - "04-14_14"
    
    # Only few unsuccesful trials 
    - "04-13_09" 
    - "04-15_10" 
    
    #Vc and df mismatch
    #- "04-16_12" 

    #- "04-19_09"
    #- "04-20_10"
    #- "04-21_11"
    #- "04-22_10"

  # Defines conditions for Gerions Experimental Setup
  conditions:
    default:
      phase: all
      n_targets: all
      n_distractors: none
      auto_reward: no
      both_spouts: yes

    #Stimulus Decoder
    #left:
    #  sides: left
    #right:
    #  sides: right

    #visual:
    #  modalities: visual
    #tactile:
    #  modalities: tactile
    #multisensory:
    #  modalities: vistact

    #Stimulus Decoder
    left_visual:
      sides: left
      modalities: visual
    right_visual:
      sides: right
      modalities: visual
    left_tactile:
      sides: left
      modalities: tactile
    right_tactile:
      sides: right
      modalities: tactile
    left_vistact:
      sides: left
      modalities: vistact
    right_vistact:
      sides: right
      modalities: vistact

# Defines trial phases for Gerions Experimental Setup
trial_conditions:
  sides:
    column: target_side_left
    conds:
      left:   1
      right:  0
  modalities:
    column: modality
    conds:
      visual:   0
      tactile:  1
      vistact:  2
  responses:
    column: response_left
    conds:
      left: 1
      right: 0
      no: -1
  n_targets:
    column: n_targets
    conds:
      all: 6
  n_distractors:
    column: n_distractors
    conds:
      none: 0
  auto_reward:
    column: auto_reward
    conds:
      no: 0
      yes: 1
  both_spouts:
    column: both_spouts
    conds:
      no: 0
      yes: 1

phase_conditions:
  pretrial:
    start: 0
    stop:  30
  posttrial:
    start: 112.5
    stop: 134
  stimulus:
    start:  30
    stop:   75
  delay:
    start: 75
    stop: 82.5
  response:
    start: 82.5
    stop: 112.5
  all:
    start: 0
    stop: 134