branch_opts:
  combine_sessions: True #True
  include_individual_sessions: False

  # Defines subjects and dates to use from Simons Experiment
  subjects:
      #mSM30:
      #  - 10-Oct-2017
      #  - 12-Oct-2017
      
      #mSM34:
      #  - 01-Dec-2017
      #  - 02-Dec-2017  
      
      #mSM36:
      #  - 05-Dec-2017
      #  - 07-Dec-2017 
      
      #mSM43:
      #  - 23-Nov-2017
      #  - 21-Nov-2017
      
      #mSM44:
      #  - 21-Nov-2017
      #  - 29-Nov-2017

      #mSM46:
      #  - 01-Dec-2017
      #  - 13-Jan-2018
      
      mSM49:
        - 12-Mar-2018
        - 19-Dec-2017

      mSM53:
        - 14-Mar-2018
        - 21-Mar-2018
      
      mSM57:
        - 08-Feb-2018
        - 02-Feb-2018

      mSM56:
        - 27-Feb-2018
        - 22-Feb-2018

      mSM55:
        - 16-Feb-2018
        - 13-Feb-2018

      mSM65:
        - 08-Sep-2018
        - 10-Sep-2018

      mSM66:
        - 08-Sep-2018
        - 10-Sep-2018
      


        

  # Defines conditions for Simon Experimental Setup
  conditions:
    default:
      phase: all

    left_vis:
      sides: left
      modalities: visual
    right_vis:
      sides: right
      modalities: visual
    left_aud:
      sides: left
      modalities: auditory
    right_aud:
      sides: right
      modalities: auditory

    ##Choice Decoder
    # leftResponse_leftStim:
    #   responses: left
    #   sides: left

    # leftResponse_rightStim:
    #   responses: left
    #   sides: right

    # rightResponse_rightStim:
    #   responses: right
    #   sides: right

    # rightResponse_leftStim:
    #   responses: right
    #   sides: left

  

# Defines trial phases for Simon Experimental Setup
trial_conditions:
  sides:
    column: CorrectSide
    conds:
      left:   1
      right:  2
  modalities:
    column: StimType
    conds:
      visual:   1
      auditory: 2
  responses:
    column: ResponseSide
    conds:
      left: 1.0
      right: 2.0

phase_conditions:
  pretrial:
    start:  0
    stop:   90
  stim1:
    start:  90
    stop:   107
  inter_stim:
    start: 107
    stop: 122
  stim2:
    start:  122
    stop:   140
  delay:
    start: 140
    stop: 170
  response:
    start: 170
    stop: 201
  #delay: #?
  #  start: 150
  #  stop: 160
  #response: #?
  #  start: 160
  #  stop: 170
  #posttrial:
  #  start: 170
  #  stop: 201
  all:
    start: 0
    stop: 201
