branch_opts:
  combine_sessions: True #Combine sessions (upon loading) & find new spatials with PCA / Combine sessions (after feature calculation) based on original spatials (noisy if spatials are different)
  include_individual_sessions: False #False #Run pipeline on individual sessions and combined sessions / just on combined session
  generalize_from: "GN06.01-20#GN06.03-01#GN06.03-02#GN06.03-03#GN06.03-04#GN06.03-05#GN06.03-26#GN06.03-29"

  subjects:
    #random:
    #  - random

    # Defines subjects and dates to use from Gerions Experiment
    GN06:
    # New Vc.mat missing
      - "01-20"
      - "03-01"
      - "03-02"
      - "03-03"
      - "03-04"
      - "03-05"

    # Working Datasets
      - "03-26"
    #  - "03-29"

    # Only few unsuccesful trials  
    #  - "04-01"

    # Old files missing
    # - "03-25"

    #GN09:
    # Working Datasets
    #  - 03-26_10
    #  - 04-14_16
    #  - 04-15_15
    #  - 04-16_15
    
    # Only few unsuccesful trials 
    #  - 04-15_11 
    #  - 04-19_10 

    # New Vc.mat missing (currently)
    #  #- 04-20_13
    #  #- 04-21_13

    #GN08:
    # Working Datasets
    #  - "03-26"
    #  - "03-29_13"

    # Only few unsuccesful trials 
    #  - "03-29_16" 

    # Old files missing
    #- 03-25_11 
    #- 03-25_15 

    # new Vc.mat missing
    # - "03-01_15"
    # - "03-02_17"
    # - "03-03"
    # - "03-04"
    # - "03-05"
    
    #GN10:
    # Working Datasets
    #- "03-29_15"
    #- "04-12_09"
    #- "04-14_14"
    
    # Only few unsuccesful trials 
    #- "04-13_09" 
    #- "04-15_10" 
    
    #Vc and df mismatch
    #- "04-16_12" 

    #- "04-19_09"
    #- "04-20_10"
    #- "04-21_11"
    #- "04-22_10"

  # Defines conditions for Gerions Experimental Setup
  conditions:
    default:
      phase: all
      n_targets: all
      n_distractors: none
      auto_reward: no
      both_spouts: yes

    #Stimulus Decoder
    #left:
    #  sides: left
    #right:
    #  sides: right

    #visual:
    #  modalities: visual
    #tactile:
    #  modalities: tactile
    #multisensory:
    #  modalities: vistact

    #Stimulus Decoder
    #L-V:
    #  sides: left
    #  modalities: visual

    #L-T:
    #  sides: left
    #  modalities: tactile

    L-VT:
      sides: left
      modalities: vistact

    #R-V:
    #  sides: right
    #  modalities: visual
    
    #R-T:
    #  sides: right
    #  modalities: tactile
    R-VT:
      sides: right
      modalities: vistact

  parcellations:
      SVD:
      LocaNMF:
      anatomical:
    
  selected_trials:
    All:


  features:

    spot-activity: #Full Timeseries for each trial
    #  phase: 
        #- all
        #- pretrial
        #- stimulus
        #- response
        
        #- stim1
        #- inter_stim
        #- stim2
        #- delay
        #- response

    full-activity: #Full Timeseries for each trial
      phase: 
        #- all
        #- pretrial
        - stimulus
        #- response

    mean-activity: #Mean Activity over trial
      phase: 
        #- all
        #- pretrial
        - stimulus
        #- stim1
        #- inter_stim
        #- stim2
        #- delay
        #- response
        #- posttrial

    #dFC:
    #  phase:
      #  - pretrial
    #    - stimulus
      #  - response

    #full-dFC:
    #  phase:
    #    - stimulus
    #  - response
    
    #FC:
    #  phase:
    #    - all
    #    - pretrial
    #    - stimulus
    #    - "?" 
        #- delay
    #    - response
        #- posttrial

    #spot-activity-dFC:
    #  phase:
      #  - pretrial
    #    - stimulus
      #  - response

    #full-activity-dFC:
    #  phase:
    #    - stimulus
      #- response
    
    #mean-activity-FC:
    #  phase:
    #    - stimulus
    #    - all
    #    - pretrial


    ##moup:
    ##  phase:
    ##    - stimulus

    #raw:
    #  max_components : [64]

    #mean:
    #  window: [1]

      #optional:
      #  window: [1] #TODO currently needs to be in an array (should support int aswell)

    #covariance:
      #max_components : [64]
    #moup:
    #  timelags: [1] #,2,3]
      #optional:
      #  thresh:
      #    - 0.5
    #  max_components : [64]

    #autocorrelation:
    #  timelags: [[1]] #,[1]]
    #  phase:
    #    - stimulus



  decoders:
    default:
      reps: [20]
    MLR:
    #MLRshuffle:

static_params:
  parcellations:
    anatomical:
    ICA:
    LocaNMF:
      minrank: 3
      maxrank: 3
      min_pixels: 400
      loc_thresh: 300
      r2_thresh: 0.99
      nonnegative_temporal: False


  selected_trials:
    All:

  features:
    mean:

  decoders:
    MLR:
    1NN:
    LDA:
    RF:

paths:
  parcellations:
    ICA: {}
    anatomical:
      atlas: resources/meta/anatomical.mat
    LocaNMF:
      atlas: resources/meta/anatomical.mat

different_config_inputs: 1

limit_memory: 1

loglevel: INFO

export_type: 'npy'



# Defines trial phases for Gerions Experimental Setup
trial_conditions:
  sides:
    column: target_side_left
    conds:
      left:   1
      right:  0
  modalities:
    column: modality
    conds:
      visual:   0
      tactile:  1
      vistact:  2
  responses:
    column: response_left
    conds:
      left: 1
      right: 0
      no: -1
  n_targets:
    column: n_targets
    conds:
      all: 6
  n_distractors:
    column: n_distractors
    conds:
      none: 0
  auto_reward:
    column: auto_reward
    conds:
      no: 0
      yes: 1
  both_spouts:
    column: both_spouts
    conds:
      no: 0
      yes: 1

phase_conditions:
  pretrial:
    start: 0
    stop:  30
  stimulus:
    start:  30
    stop:   75
  delay:
    start: 75
    stop: 82
  response:
    start: 82
    stop: 113
  posttrial:
    start: 113
    stop: 134
  all:
    start: 0
    stop: 134
