name: calcium_imaging_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.23.3
  - pandas
  - scipy

  - scikit-learn = 1.2.0

  - matplotlib=3.5.3
  - bokeh

  - pyyaml
  - pytables
  - opencv
  - pycairo

  - pip:
      - umap-learn
      - hdbscan

      - networkx
      - Shapely
      - seaborn>=0.12.2
      - plotly
      - kaleido
            
      - psutil # ?

      # Windows workaround for h5py
      - wheel
      - cython
      - versioned-hdf5
      - h5py

variables:
  SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL: True #While we use old pyMOU

