name: locanmf
channels:
  - conda-forge
  - defaults
  - local
dependencies:
  - python>=3.8
  - pip
  - numpy
  - pandas=2.0.3
  - scipy


  - scikit-learn

  - matplotlib
  - bokeh

  - pyyaml
  - pytables>=3.5.1
  - opencv
  - locanmf

  - pip:
      - pyMou@git+https://github.com/mb-BCA/pyMOU.git@master

      - networkx
      - Shapely
      - seaborn==0.12.2
      
      # ?
      - psutil

      # Windows workaround for h5py
      - wheel
      - cython
      - versioned-hdf5
      - h5py
      - wfield

