name: locanmf
channels:
  - conda-forge
  - defaults
  - local
dependencies:
  - python=3.7
  - pip
  - numpy
  - pandas
  - scipy


  - scikit-learn

  - matplotlib
  - bokeh

  - pyyaml
  - pytables>=3.5.1
  - opencv
  - locanmf

  - pip:
      - pyMou@git+https://github.com/mb-BCA/pyMOU.git@master

      - networkx
      - Shapely

      # ?
      - psutil

      # Windows workaround for h5py
      - wheel
      - cython
      - versioned-hdf5
      - h5py

