branch_opts:
  combine_sessions: True #Combine sessions (upon loading) & find new spatials with PCA / Combine sessions (after feature calculation) based on original spatials (noisy if spatials are different)
  include_individual_sessions: False #False #Run pipeline on individual sessions and combined sessions / just on combined session
  generalize_from: "GN06.01-20#GN06.03-01#GN06.03-02#GN06.03-03#GN06.03-04#GN06.03-05#GN06.03-26#GN06.03-29"

    
    #GN06_untrained combined im shared_space von untrained
    #Gn06_untrained ind      im shared_space  
    #Gn06_untrained ind      im ind_space    

    




  subjects:
    #random:
    #  - random

    # Defines subjects and dates to use from Gerions Experiment
    GN06:
    #  - "10-29_18-45-37"
      - "10-30_14-10-39"
      - "11-02_18-30-49"
    #  - "11-03_14-51-40"
      - "11-03_15-11-40"
      - "11-04_14-13-23"
      - "11-05_17-01-25"
    #  - "11-09_16-39-17"
    #  - "11-10_14-50-02"
    #  - "11-11_13-45-55"
    #  - "11-12_15-52-36"
    #  - "11-13_15-45-13"
    #  - "11-16_11-33-49"
    #  - "11-16_15-26-28"
    #  - "11-17_11-16-15"
    #  - "11-18_14-00-56"
    #  - "11-19_14-56-33"
    #  - "11-20_14-41-44"
    #  - "11-23_14-57-41"
    #  - "11-24_15-23-17"
    #  - "11-25_14-18-27"
    #  - "11-26_15-07-46"
    #  - "11-27_15-02-16"
    #  - "11-30_13-17-29"
    #  - "12-01_12-10-02"
    #  - "12-02_13-54-27"
    #  - "12-03_15-22-47"
    #  - "12-04_15-02-58"
    #  - "12-07_12-13-17"
    #  - "12-08_11-06-22"
    #  - "12-09_11-18-31"
    #  - "12-11_10-53-04"

    GN08:
    #  - "10-29_17-05-48" #only few trials + trials with only 36frames
      - "10-29_17-11-46"
      - "10-30_13-03-25"
      - "11-02_16-49-52"
      - "11-03_12-46-12"
      - "11-04_16-42-36"
    #  - "11-05_15-24-42" #df vc missmatch
      - "11-05_15-36-17"
    #  - "11-09_17-25-21"
    #  - "11-10_16-56-46"
    #  - "11-11_15-49-03"
    #  - "11-12_17-14-56"
    #  - "11-13_17-48-40"
    #  - "11-16_12-19-15"
    #  - "11-16_16-03-03"
    #  - "11-17_12-44-26"
    #  - "11-18_14-47-29"
    #  - "11-19_15-54-26"
    #  - "11-20_16-05-26"
    #  - "11-23_16-09-22"
    #  - "11-24_16-56-52"
    #  - "11-25_17-55-53"  
    #  - "11-26_16-01-49"
    #  - "11-27_14-20-17"
    #  - "11-30_14-03-58"
    #  - "12-01_13-32-03"
    #  - "12-02_14-17-49"
    #  - "12-03_17-08-02"
    #  - "12-04_16-42-31"
    #  - "12-07_10-59-56"
    #  - "12-08_11-46-54"
    #  - "12-09_12-14-23"
    #  - "12-10_10-52-03"
    #  - "12-10_11-22-27"

  conditions:
  
    default:
      phase: all
      #n_targets: all
      #n_distractors: none
      auto_reward: no
      both_spouts: yes
      

    LR-LS:
      responses: left
      sides: left

    LR-RS:
      responses: left
      sides: right
      

    RR-LS:
      responses: right
      sides: left

    RR-RS:
      responses: right
      sides: right

    LeftChoice:
      group:
        - LR-LS
        - LR-RS

    RightChoice:
      group:
        - RR-RS
        - RR-LS
  

    #Correct:
    #  group:
    #    - LR-LS
    #    - RR-RS
    #Incorrect:
    #  group:
    #    - LR-RS
    #    - RR-LS
  
  parcellations:
    SVD:
    #  n_components: 
    #    - 299
    LocaNMF:
    anatomical:
    
  selected_trials:
    All:


  features:

    spot-activity: #Full Timeseries for each trial
      #phase: 
        #- all
        #- pretrial
      #  - stimulu s
        #- response
        
        #- stim1
        #- inter_stim
        #- stim2
        #- delay
        #- response

    #full-activity: #Full Timeseries for each trial
      #phase: 
        #- all
        #- pretrial
        #- stimulus
        #- response

    #mean-activity: #Mean Activity over trial
      #phase: 
        #- all
        #- pretrial
        #- stimulus
        #- stim1
        #- inter_stim
        #- stim2
        #- delay
        #- response
        #- posttrial

    #dFC:
    #  phase:
      #  - pretrial
    #    - stimulus
      #  - response

    #full-dFC:
    #  phase:
    #    - stimulus
    #  - response
    
    #FC:
    #  phase:
    #    - all
    #    - pretrial
    #    - stimulus
    #    - "?" 
        #- delay
    #    - response
        #- posttrial

    #spot-activity-dFC:
    #  phase:
      #  - pretrial
    #    - stimulus
      #  - response

    #full-activity-dFC:
    #  phase:
    #    - stimulus
      #- response
    
    #mean-activity-FC:
    #  phase:
    #    - stimulus
    #    - all
    #    - pretrial


    ##moup:
    ##  phase:
    ##    - stimulus

    #raw:
    #  max_components : [64]

    #mean:
    #  window: [1]

      #optional:
      #  window: [1] #TODO currently needs to be in an array (should support int aswell)

    #covariance:
      #max_components : [64]
    #moup:
    #  timelags: [1] #,2,3]
      #optional:
      #  thresh:
      #    - 0.5
    #  max_components : [64]

    #autocorrelation:
    #  timelags: [[1]] #,[1]]
    #  phase:
    #    - stimulus



  decoders:
    default:
      reps: [5]
    MLR:
    #MLRshuffle:

static_params:
  parcellations:
    anatomical:
    ICA:
    LocaNMF:
      minrank: 2
      maxrank: 8
      min_pixels: 400
      loc_thresh: 300
      r2_thresh: 0.99
      nonnegative_temporal: False


  selected_trials:
    All:

  features:
    mean:

  decoders:
    MLR:
    1NN:
    LDA:
    RF:

paths:
  parcellations:
    ICA: {}
    anatomical:
      atlas: resources/meta/anatomical.mat
    LocaNMF:
      atlas: resources/meta/anatomical.mat

different_config_inputs: 1

limit_memory: 1

loglevel: INFO

export_type: 'npy'



# Defines trial phases for Gerions Experimental Setup
trial_conditions:
  sides:
    column: target_side_left
    conds:
      left:   1
      right:  0
  modalities:
    column: modality
    conds:
      visual:   0
      tactile:  1
      vistact:  2
  responses:
    column: response_left
    conds:
      left: 1
      right: 0
      no: -1
  n_targets:
    column: n_targets
    conds:
      all: 6
  n_distractors:
    column: n_distractors
    conds:
      none: 0
  auto_reward:
    column: auto_reward
    conds:
      no: 0
      yes: 1
  both_spouts:
    column: both_spouts
    conds:
      no: 0
      yes: 1

phase_conditions:
  pretrial:
    start: 0
    stop:  30
  stimulus:
    start:  30
    stop:   75
  delay:
    start: 75
    stop: 82
  response:
    start: 82
    stop: 113
  posttrial:
    start: 113
    stop: 134
  all:
    start: 0
    stop: 134
